---
title: "Homework 2"
author: "Ama Konadu Appau & Akash Agrawal Bejarano"
date: "2/2/2023"
output: word_document
---
```{r}
library(tidyverse)
library(dplyr)
```

Question 1
```{r}
logFunction <- function(n){
  return(sum(log(n)+log10(n)+log2(n)))
}
logFunction(2)
logFunction(4)
logFunction(6)
logFunction(8)
logFunction(10)
```
Question 2
```{r}
bigNumber <- function(n){
  if(n^2 >=100){
    print("This is a big number")
  }
  else{
    print("This is not a big number")
  }
}

bigNumber(20)
bigNumber(4)
```
Question 3
```{r}
team_A <- 2
team_B <- 2

if (team_A > team_B){
  print ("Team A won")
} else if (team_A < team_B){
  print ("Team B won")
} else {
  "Team A won" ## changed this line to say team a won
}

```

Question 4

```{r}
divisible <- function(n){
  if(n%%3 == 0 & n %% 5 == 0){
    print("divisible by Three and Five")
  }
  else if(n %%3 == 0 & n %%4 == 0){
    print("divisible by Three and Four")
  }
  else{
    print("neither")
  }
}
divisible(16)
divisible(45)
divisible(24)
```

## Question 5

```{r}
data5 <- mpg %>% select(displ, cyl, cty, hwy)
output <- vector("double", ncol(data5))  # 1. output
 for (i in seq_along(data5)) {            # 2. sequence
   output[[i]] <- var(data5[[i]])      # 3. body
 }
 output
```

## Question 6

```{r}
prime <- function(num){
   if (num == 2) {
      return(TRUE)}
  else if (any(num %%2:(num-1) ==0)) {
      return(FALSE)}
  else { 
      return(TRUE)}}

for( i in 10:30){
  if( prime(i) == TRUE){
    print(i^3 - i^2)}}
```