---
title: "Homework 3"
author: "Ama Konadu Appau & Akash Agrawal Bejarano"
date: "2/2/2023"
output: word_document
---
```{r}
library(tidyverse)
library(dplyr)
Vector1 <- (c( 10, 19, 121, 83, 63, 7, 77, 61, 51, 97, 123, 41))
Vector1
```

## Question 1

```{r}
Vector1[c(1,12)]
Vector1[-c(2,3,4,5,6,7,8,9,10,11)]
```

## Question 2

```{r}
Vector1[Vector1 < 60]
for(i in Vector1){
  if(i < 60){
    print(i)
  }
}
```

## Question 3

```{r}
Vector1[Vector1 %% 2 != 0 & Vector1 %% 3 != 0]
for(i in Vector1){
  if(i %% 3 != 0 & i %% 2 != 0){
    print(i)
  }
}
```
## Question 4

```{r}
is.na(Vector1)
Vector1[Vector1=="NA"]
```
## Question 5

```{r}
myList <-  list(TRUE, 12.35, "pear", 48, c = 3:8, list(23, "team"))
str(myList[[3]])
```
## Question 6

```{r}
myList[1:3]
```
## Question 7

```{r}
myList <-  list(TRUE, 12.35, k = "pear", 48, c = 3:8, list(23, "team"))
myList$k
```

## Question 8

```{r}
quad <- function(a, b, c){
   x1 <- ((b * -1) + sqrt(b^2 - (4*a*c)))/(2*a)
   x2 <- ((b * -1) - sqrt(b^2 - (4*a*c)))/(2*a)
   print(paste("roots are", x1, "and", x2))
}
#equation 1
quad(1,-3,-28)

#equation 2
quad(1,1,-30)

#Question 3
quad(3,14,8)

#question 4
quad(2,11,0)
```

## Question 9

```{r}
tb <- tibble(x = 1:10, y = 10:1, z = y/2)
tb
```
## Question 10

```{r}
tb %>%
  map_dbl(IQR)
```

